version: '3.8'

services:

  #PHP Service
  app:
    build:
      context: "./fpm/"
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - "../:/var/www/html"
    depends_on:
      - db
      - redis
      - laravel_echo_server

  #Nginx Service
  webserver:
    image: "nginx"
    restart: unless-stopped
    ports:
      # - "${APP_PORT}:80"
      - "80:80"
      - "6001:6001"
    volumes:
      - "../:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

  # DB UI management service
  adminer:
    image: "phpmyadmin:latest"
    restart: unless-stopped
    ports:
      # - ${ADMINER_PORT}:8080
      - "85:80"
    depends_on:
      - db

  #MySQL Service
  db:
    image: "mysql:8.0"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laraveluserpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - "./data/db:/var/lib/mysql/"

  laravel_echo_server:
    build:
      context: "./echo"
      dockerfile: Dockerfile
    volumes:
      - "../env:/app/.env"
      - "./echo/laravel-echo-server.json:/app/laravel-echo-server.json"
    restart: unless-stopped

  redis:
    image: "redis"
    expose:
      - "6379"
    volumes:
      - "./data/redis:/data"
      - "./redis/redis.conf:/etc/redis/redis.conf"
    restart: unless-stopped
